org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true

kotlin.code.style=official

codeArtifact.domain=yossibank
codeArtifact.owner=724669215656
codeArtifact.region=ap-northeast-1
codeArtifact.repository=kmp

org.gradle.tooling.parallel=true
